-- The database is an index over portable documents, not a second source of truth.
-- Every list is stored whole as JSONB exactly as core/validate.ts produced it; the
-- columns beside it exist only so we can find, sort and filter without parsing.

create extension if not exists pg_trgm;

create table if not exists profiles (
  handle     text primary key,
  name       text not null,
  bio        text,
  link       text,
  user_id    text unique,
  created_at timestamptz not null default now()
);

-- Idempotent for databases created before sign-in existed.
alter table profiles add column if not exists user_id text unique;

create table if not exists lists (
  id          text not null,
  handle      text not null references profiles (handle) on delete cascade,
  slug        text not null,
  visibility  text not null default 'public' check (visibility in ('public', 'unlisted')),
  doc         jsonb not null,
  search_text text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  primary key (handle, slug)
);

create index if not exists lists_feed_idx on lists (updated_at desc) where visibility = 'public';
create index if not exists lists_search_idx on lists using gin (search_text gin_trgm_ops);

-- Better Auth owns these four tables (generated by `better-auth/cli generate`, made
-- idempotent). Google is the only provider; `password` stays empty.
create table if not exists "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);
create table if not exists "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);
create table if not exists "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);
create table if not exists "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);
create index if not exists "session_userId_idx" on "session" ("userId");
create index if not exists "account_userId_idx" on "account" ("userId");
create index if not exists "verification_identifier_idx" on "verification" ("identifier");
